### ISSUE TITLE
Setup Variables (umbrella)

### ISSUE THREAD

**Issue by dalonsoa** [ImperialCollegeLondon/virtual_ecosystem#389]
Ok, so I'm booking myself Thursday and Friday next week to work on this. My plan would be:

### Step 1 (one PR)
- [x] Start from the simplified version created by @davidorme 
- [x] Add a step [somewhere in the `Config` class](https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/76f19065815edc8eebdef6016b94859123697847/virtual_rainforest/core/config.py#L129) after the required models have been pulled out of the configuration to populate the `initialised_by`, `updated_by`, and `used_by` lists. The models might need updating.
- [x] Run some validation based initially on the following conditions, raising an error if they are broken:
    - [x] No variable is initialised by two models
    - [x] There is no variable used or updated that has not been initialised
    - [x] No two models update the same variable (or they do, I don't know if that is a use case)

### Step 2 (another PR, after the above is merged)
- [x] Update the [`get_model_sequence`](https://github.com/ImperialCollegeLondon/virtual_rainforest/blob/76f19065815edc8eebdef6016b94859123697847/virtual_rainforest/main.py#L62) function to use this information, as well as (or in place of?) the explicit dependencies already in place, to try to come up with the right sequence.
- [x] Update the models so they initialise the variables when they are initialised and the registry of initialised variables is populated.

### Step 3 (yet another PR)
- Update the models so they use the information from this registry -> TBC by each model at its own pace

I'm sure I'm missing something and I will need to improvise, but is there anything obvious I'm forgetting?

_Originally posted by @dalonsoa in https://github.com/ImperialCollegeLondon/virtual_rainforest/issues/371#issuecomment-1934300630_

**Comment by davidorme** [comment]
@dalonsoa Where are we on this meta issue? I think it's all done _apart_ from the `get_model_sequence` replacement?

**Comment by dalonsoa** [comment]
Yes, that's all that is left, aside from using the variables, but that's more for each individual model to adopt.

I'll see if I can tackle the `get_model_sequence` before the end of this week.
